name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve LLMLingua
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:

        1. Step 1
        2. Step 2
        3. ...
        4. See error
      placeholder: How can we replicate the issue?
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs or screenshots to help explain your problem.
      placeholder: Add logs here
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: |
        - LLMLingua Version: <!-- Specify the LLMLingua version (e.g., v0.1.0) -->
        - Operating System: <!-- Specify the OS (e.g., Windows 10, Ubuntu 20.04) -->
        - Python Version: <!-- Specify the Python version (e.g., 3.8) -->
        - Related Issues: <!-- Link to any related issues here (e.g., #1) -->
        - Any other relevant information.
      placeholder: Any additional details
