"""

Module version

This module defines the version information for the software. The version is
constructed using semantic versioning, represented by three numerical components:
major, minor, and patch, as well as an optional suffix for pre-release versions.

Attributes:
    _MAJOR (str): The major part of the version indicating fundamental changes
        to the software, with backwards-incompatible alterations typically. This
        value should be incremented for such significant changes.
    _MINOR (str): The minor part of the version indicating incremental
        improvements and additions to the software. This value is incremented
        for backwards-compatible enhancements.
    _PATCH (str): The patch part of the version reflecting bug fixes and minor
        changes which do not add or remove any functionality in a backwards-
        incompatible way. This is incremented for each bug fix release.
    _SUFFIX (str): An optional suffix for the version that might be used in
        nightly builds or pre-releases. This follows the conventions of
        semantic versioning pre-release notation.
    VERSION_SHORT (str): A shortened version string using the major and minor
        components only. Useful for a broad overview of the version when the
        patch level or suffix isn't necessary.
    VERSION (str): The full version string, incorporating the major, minor,
        and patch components, as well as the suffix if it is present.

This module is utilitarian by design and provides a centralized place to keep
track of version information that can be used throughout the software to
conditionally manipulate behavior or display the current version to end-users.

Note: Documentation automatically generated by https://undoc.ai
"""
_MAJOR = "0"
_MINOR = "1"
# On master and in a nightly release the patch should be one ahead of the last
# released build.
_PATCH = "4"
# This is mainly for nightly builds which have the suffix ".dev$DATE". See
# https://semver.org/#is-v123-a-semantic-version for the semantics.
_SUFFIX = ""

VERSION_SHORT = "{0}.{1}".format(_MAJOR, _MINOR)
VERSION = "{0}.{1}.{2}{3}".format(_MAJOR, _MINOR, _PATCH, _SUFFIX)
