 # This workflows will build and upload a Python Package using Twine when a release is published
# Conda-forge bot will pick up new PyPI version and automatically create new version
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: release
run-name: Release LLMLingua by @${{ github.actor }}

on:
  release:
    types: [published]
permissions: {}

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    environment:
      name: pypi
      url: https://pypi.org/project/llmlingua/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install from source
        # This is required for the pre-commit tests
        shell: pwsh
        run: pip install .

      - name: Build
        shell: pwsh
        run: |
          pip install twine wheel
          python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
